name: Build Vue app to other branch
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    name: Build to other branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install all dependencies
      run: npm install

    - name: Build
      run: npm run build # The build command of your project

    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: deploy
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_DIR: frontend
