name: Build Vue app to other branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build to other branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install all dependencies
      run: npm install
      working-directory: frontend

    - name: Build
      run: npm run build # The build command of your project
      working-directory: frontend

    - name: Push frontend
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: deploy
        FOLDER: frontend/dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push backend
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: deploy
        FOLDER: backend
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_DIR: backend

    - name: Copy .htaccess
      env:
        TARGET_BRANCH: 'deploy'
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git fetch                         # Fetch branches
        git checkout $TARGET_BRANCH       # Checkout to your branch
        git checkout main .htaccess # Copy files from the source branch
        git add .htaccess
        git diff-index --quiet HEAD ||  git commit -am "Deploy files"  # Commit to the repository (ignore if no modification)
        git push origin $TARGET_BRANCH # Push to remote branch

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2

    - name: Install Composer Dependencies
      run: |
        composer install --no-dev --optimize-autoloader
      working-directory: deploy